import { Product } from './types';

export const products: Product[] = [
  {
    id: "AI-001",
    name: "AI-Generated Fortune Cookies",
    price: 9.99,
    image: window.location.origin + "/images/ai-fortune-cookies.webp",
    description: `<p>Indulge in our <strong>AI-Generated Fortune Cookies</strong>, where every cookie contains a unique, humorous fortune created by artificial intelligence. Perfect for parties, gifts, or just a good laugh!</p>`,
  },
  {
    id: "AI-002",
    name: "Robo Chef Recipe Book",
    price: 14.99,
    image: window.location.origin + "/images/robo-chef-cookbook.webp",
    description: `<p>Cook up a storm with the <strong>Robo Chef Recipe Book</strong>. This colorful cookbook features recipes curated by an AI chef, ensuring delicious and innovative dishes every time!</p>`,
  },
  {
    id: "AI-003",
    name: "ChatGPT Conversation Starters",
    price: 7.99,
    image: window.location.origin + "/images/conversation-starters-cards.webp",
    description: `<p>Break the ice with the <strong>ChatGPT Conversation Starters</strong>. This set of cards offers engaging and fun prompts generated by AI, making sure you never run out of things to talk about.</p>`,
  },
  {
    id: "AI-004",
    name: "Deep Learning Coffee Mug",
    price: 12.99,
    image: window.location.origin + "/images/ai-mug.webp",
    description: `<p>Start your day with a boost of intellect using the <strong>Deep Learning Coffee Mug</strong>. Featuring a neural network design, this sleek mug is perfect for all AI enthusiasts and coffee lovers.</p>`,
  },
  {
    id: "AI-005",
    name: "AI Art Generator Kit",
    price: 24.99,
    image: window.location.origin + "/images/ai-art-kit.webp",
    description: `<p>Unleash your creativity with the <strong>AI Art Generator Kit</strong>. This kit includes everything you need to create stunning AI-generated artwork, perfect for artists and tech lovers alike.</p>`,
  },
  {
    id: "AI-006",
    name: "Machine Learning Socks",
    price: 11.99,
    image: window.location.origin + "/images/machine-learning-socks.webp",
    description: `<p>Keep your feet warm and your mind sharp with the <strong>Machine Learning Socks</strong>. These cozy socks feature fun patterns inspired by neural networks and data science.</p>`,
  },
  {
    id: "AI-007",
    name: "AI-Enhanced Puzzle Set",
    price: 19.99,
    image: window.location.origin + "/images/ai-puzzle.webp",
    description: `<p>Challenge your mind with the <strong>AI-Enhanced Puzzle Set</strong>. This set features a vibrant AI-generated landscape that will keep you engaged for hours.</p>`,
  },
  {
    id: "AI-008",
    name: "Neural Network T-shirt",
    price: 17.99,
    image: window.location.origin + "/images/ai-t-shirt.webp",
    description: `<p>Show off your love for AI with the <strong>Neural Network T-shirt</strong>. This stylish tee features a modern design of a neural network diagram, perfect for any tech enthusiast.</p>`,
  },
];
